language: nodejs

before_script:
  - yarn install
  - yarn build

script:
  - yarn test

after_success:
  - yarn typedoc
  - yarn pack

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "amp-css-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: $NPM_MAIL
    api_key: $NPM_TOKEN
    on:
      tags: true